#!/usr/bin/env bash
#
# Sync the shared sources into every steps/*/ directory.
#
# Each published Step has to be a self-contained repository, so the shared
# helpers are physically copied into each step.sh between the markers below, and
# the LICENSE and .gitignore are copied alongside. Run this after editing
# lib/testingbot.bash, and commit the result.
#
# Usage:
#   scripts/build.sh          # rewrite every step.sh
#   scripts/build.sh --check  # fail if any step.sh is out of date (for CI)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIB="${REPO_ROOT}/lib/testingbot.bash"

BEGIN_MARK='# >>> BEGIN inlined lib/testingbot.bash -- generated by scripts/build.sh; do not edit >>>'
END_MARK='# <<< END inlined lib/testingbot.bash <<<'

CHECK_ONLY=false
[ "${1:-}" = "--check" ] && CHECK_ONLY=true

if [ ! -f "$LIB" ]; then
  echo "error: $LIB not found" >&2
  exit 1
fi

# The inlined copy drops the library's shebang.
LIB_BODY="$(mktemp)"
trap 'rm -f "$LIB_BODY"' EXIT
sed '1{/^#!/d;}' "$LIB" >"$LIB_BODY"

status=0
found=0

for step_sh in "${REPO_ROOT}"/steps/*/step.sh; do
  [ -e "$step_sh" ] || continue
  found=$((found + 1))
  step_id="$(basename "$(dirname "$step_sh")")"

  if ! grep -qF "$BEGIN_MARK" "$step_sh" || ! grep -qF "$END_MARK" "$step_sh"; then
    echo "error: ${step_id}/step.sh is missing the inline markers" >&2
    status=1
    continue
  fi

  rendered="$(mktemp)"
  awk -v libfile="$LIB_BODY" -v begin_mark="$BEGIN_MARK" -v end_mark="$END_MARK" '
    index($0, begin_mark) == 1 {
      print
      while ((getline line < libfile) > 0) print line
      close(libfile)
      skipping = 1
      next
    }
    index($0, end_mark) == 1 { skipping = 0; print; next }
    !skipping { print }
  ' "$step_sh" >"$rendered"

  if cmp -s "$rendered" "$step_sh"; then
    rm -f "$rendered"
    continue
  fi

  if $CHECK_ONLY; then
    echo "out of date: steps/${step_id}/step.sh (run scripts/build.sh)" >&2
    rm -f "$rendered"
    status=1
  else
    cat "$rendered" >"$step_sh"
    chmod +x "$step_sh"
    rm -f "$rendered"
    echo "updated: steps/${step_id}/step.sh"
  fi
done

if [ "$found" -eq 0 ]; then
  echo "warning: no steps/*/step.sh found" >&2
fi

# --- shared files copied verbatim into each step directory -------------------

sync_file() {
  # sync_file <source> <path-relative-to-step-dir>
  local src="$1" name="$2" step_dir step_id dest
  for step_dir in "${REPO_ROOT}"/steps/*/; do
    [ -d "$step_dir" ] || continue
    step_id="$(basename "$step_dir")"
    dest="${step_dir}${name}"
    if cmp -s "$src" "$dest" 2>/dev/null; then
      continue
    fi
    mkdir -p "$(dirname "$dest")"
    if $CHECK_ONLY; then
      echo "out of date: steps/${step_id}/${name} (run scripts/build.sh)" >&2
      status=1
    else
      cp "$src" "$dest"
      echo "updated: steps/${step_id}/${name}"
    fi
  done
}

sync_file "${REPO_ROOT}/LICENSE" LICENSE
sync_file "${REPO_ROOT}/.gitignore" .gitignore
sync_file "${REPO_ROOT}/shared/docs/contributing.md" docs/contributing.md

# READMEs are generated by Bitrise's own steps-readme-generator rather than here,
# because the StepLib expects its exact format. It needs the Bitrise CLI and
# network access, so it lives in scripts/gen-readme.sh and is run on release.

exit "$status"
